FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y python
RUN apt-get install -y git
RUN apt-get install -y vim
RUN git clone https://github.com/gitferry/PoR.git
RUN cd PoR/core/
EXPOSE 65535
